name: Stock Bot Scheduler

on:
  workflow_dispatch:
  schedule:
    - cron: '0 4 * * 1'   # Every Monday
    - cron: '0 4 1 * *'   # 1st of every month

jobs:
  run-bot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Libraries
        run: python -m pip install yfinance pandas numpy ta openpyxl

      - name: Debug files before run
        run: ls

      - name: Run Bot
        run: python stock_bot_monthly.py

      - name: Debug files after run
        run: ls

      - name: Upload Excel File
        uses: actions/upload-artifact@v4
        with:
          name: bot-output
          path: portfolio.xlsx
